name: Build and Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
      working-directory: ./FHIRWebApi.Angular.FrontEnd

    - name: Build Angular app (prod)
      run: |
        npm run build -- --configuration production --base-href "/${{ github.event.repository.name }}/"
        mkdir -p ../../docs
        cp -r ./dist/* ../../docs/
      working-directory: ./FHIRWebApi.Angular.FrontEnd

    - name: Commit built site to /docs
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@users.noreply.github.com'
        git add docs
        git commit -m "Deploy to /docs [skip ci]" || echo "No changes to commit"
        git push
