name: Build and Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Debug: list files
      run: |
        cd FHIRWebApi.Angular.FrontEnd
        ls -la

    - name: Install dependencies
      working-directory: ./FHIRWebApi.Angular.FrontEnd
      run: npm install

    - name: Build Angular app (prod)
      working-directory: ./FHIRWebApi.Angular.FrontEnd
      run: |
        npm run build -- --configuration production --base-href "/${{ github.event.repository.name }}/"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: FHIRWebApi.Angular.FrontEnd/dist
        enable_jekyll: false
